config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  resources :home
  root :to => redirect('/home')
  get '/selcat', to: 'selcat#index'
  get '/quiz', to: 'quiz#index'
  
  resources :selcat
  get '/practice', to: 'practice#index'
  
  resources :selquiz
  get '/quiz', to: 'practice#index'
  
  resources :admin
  
  resources :practice
  get '/index', to: 'practice#index'
  
  resource :quiz
  
  resources :sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  get '/index', to: 'users#show'
  
  resources :questions

  get 'new_question' => 'questions#new'

end

app/models/question_bank.rb
class QuestionBank < ActiveRecord::Base
    def self.category
        return ['Networks', 'Algorithms', 'Operating Systems', 'Software']
    end
    
    def self.quizLimit
    return ['20','40','60', 'All']
    end
    
end

app/models/user.rb
class User < ActiveRecord::Base
    
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
def index
end

end

app/controllers/practice_controller.rb
class PracticeController < ApplicationController
    
    # def question_params
    #     params.require(:question_bank).permit(:category, :question, :option1, :option2, :option3, :option4, :option5, :answer)
    # end

    def index
        if params[:categories].present?
            @questions = QuestionBank.where(category: params[:categories].keys)
        end
    end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    
    before_action :logged_in_user, only: [:create, :new, :index]
    
    def question_params
        params.require(:question).permit(:category, :question, :option1, :option2, :option3, :option4, :option5, :answer,:image1,:image2,:image3,:image4,:image5,:imagequestion)
    end
    
    def index
        @questions = QuestionBank.all
    end
    
    def create
         @question = QuestionBank.create!(question_params)

        if params[:imagequestion].present?
            preloaded = Cloudinary::PreloadedFile.new(params[:imagequestion])
            @question.update(question: preloaded.identifier)
        end
        if params[:image1].present?
            preloaded = Cloudinary::PreloadedFile.new(params[:image1])
            @question.update(option1: preloaded.identifier)
        end
        if params[:image2].present?
            preloaded = Cloudinary::PreloadedFile.new(params[:image2])
            @question.update(option2: preloaded.identifier)
        end
        if params[:image3].present?
            preloaded = Cloudinary::PreloadedFile.new(params[:image3])
            @question.update(option3: preloaded.identifier)
        end
        if params[:image4].present?
            preloaded = Cloudinary::PreloadedFile.new(params[:image4])
            @question.update(option4: preloaded.identifier)
        end
        if params[:image5].present?
            preloaded = Cloudinary::PreloadedFile.new(params[:image5])
            @question.update(option5: preloaded.identifier)
        end
       
        flash[:success] = "Question was successfully added"
        redirect_to questions_path
    end
    
    def edit
        @question = QuestionBank.find(params[:id])
       # redirect_to questions_path(@question)
    end
    
    def update

        @question = QuestionBank.find(params[:id])
        @question.update_attributes!(question_params)
        if params[:imagequestion].present?
            preloaded = Cloudinary::PreloadedFile.new(params[:imagequestion])
            @question.update(question: preloaded.identifier)
        end
        if params[:image1].present?
            preloaded = Cloudinary::PreloadedFile.new(params[:image1])
            @question.update(option1: preloaded.identifier)
        end
        if params[:image2].present?
            preloaded = Cloudinary::PreloadedFile.new(params[:image2])
            @question.update(option2: preloaded.identifier)
        end
        if params[:image3].present?
            preloaded = Cloudinary::PreloadedFile.new(params[:image3])
            @question.update(option3: preloaded.identifier)
        end
        if params[:image4].present?
            preloaded = Cloudinary::PreloadedFile.new(params[:image4])
            @question.update(option4: preloaded.identifier)
        end
        if params[:image5].present?
            preloaded = Cloudinary::PreloadedFile.new(params[:image5])
            @question.update(option5: preloaded.identifier)
        end
        flash[:success] = "Question-#{@question.id} was successfully updated."
        redirect_to questions_path(@question)
    end
    
    def destroy
        @question = QuestionBank.find(params[:id])
        @question.destroy
        flash[:destroy] = "Question-'#{@question.id}' deleted."
        redirect_to questions_path
    end
    
    private
    
        # Confirms a logged-in user.
        def logged_in_user
          unless logged_in?
            flash[:danger] = "Please log in."
            redirect_to login_url
          end
        end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
    
    def index
        if params[:quizlimit] == "All"
         @questions= QuestionBank.all
        
        else
            @questions= QuestionBank.all.sample(params[:quizlimit].to_i)
        end
    end
end

app/controllers/selcat_controller.rb
class SelcatController < ApplicationController
    
    def index
        @all_categories = QuestionBank.category
    end
    
end

app/controllers/selquiz_controller.rb
class SelquizController < ApplicationController
    
    def index
        @quizlimit=QuestionBank.quizLimit
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  
  def show
   redirect_to questions_path
  end
  
  
  def new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/practice_helper.rb
module PracticeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/quiz_helper.rb
module QuizHelper
end

app/helpers/selcat_helper.rb
module SelcatHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !current_user.nil?
    end
    
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

#RSpec.configure do |config|
#    config.include SessionsHelper
#end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
.container.jumbotron
  .text-center
    %h1 Welcome to the PhDQual Flash Cards
  .row
    .mx-auto
      = link_to "Start Practice", selcat_path, class: "btn btn-lg btn-primary"
      = link_to "Start Quiz", selquiz_index_path, class: "btn btn-lg btn-primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title Flash Cards: Home
    
    / jQuery library
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"}

    / Latest compiled and minified CSS
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css", :rel => "stylesheet"}/
   
    / Latest compiled JavaScript
    %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false
    = javascript_include_tag 'application', 'data-turbolinks-track' => false
    = csrf_meta_tags
    
  %body
    %nav.navbar.navbar-expand-md.bg-dark.navbar-dark
      %a.navbar-brand{:href => "#"} PhD Flash Cards
      %button.navbar-toggler{"data-target" => ".dual-collapse2", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      .collapse.navbar-collapse.w-100.order-1.order-md-0.dual-collapse2
        %ul.navbar-nav.mr-auto
          %li.nav-item
            %a.nav-link{:href => "/home"}
              Home
              %span.sr-only (current)
          %li.nav-item
            %a.nav-link{:href => "/selcat"} Practice
          %li.nav-item
            %a.nav-link{:href => "/selquiz"} Quiz
      .navbar-collapse.collapse.w-100.order-3.dual-collapse2
        - if logged_in?
          %ul.navbar-nav.ml-auto
            %li.nav-item
              %a.nav-link{:href => "/questions"} Questions
            %li.nav-item
              = link_to "Log out", logout_path, method: :delete, class:"nav-link"
        - else
          %ul.navbar-nav.ml-auto
            %li.nav-item
              %a.nav-link{:href => login_path} Login
          
    %br/
    = yield
    %br/
    %footer.footer.bg-dark
      .container
        %span.text-muted Created by Team RubyGeeks

app/views/practice/index.html.haml
.container
  .row
    .col-md-12#quizContainer
      %article.jumbotron.mx-auto
        - @questions.each_with_index do |ques,index|
          .questionItem{:class=>"#{'hide' if index > 0}","data-answer" => "#{ques.answer}","data-index"=>"#{index}"}
            .row
              %span.h--serif Category: #{ques.category} | Question #{index+1} of #{@questions.count}
            .row
              - if /.(jpeg|jpg|gif|png)$/.match(ques.question)
                = cl_image_tag(ques.question,:class=>"img-thumbnail img-fluid")
              - else
                %h3= ques.question
            .row
              .choices
                .radio
                  %label
                    %input{:name => "optradio#{index}","data-index"=>"0", :type => "radio",:class=>"option"}/
                  - if /.(jpeg|jpg|gif|png)$/.match(ques.option1)
                    = cl_image_tag(ques.option1,:class=>"img-thumbnail img-fluid")
                  - else
                    %font{:size => "4.5"}= ques.option1
                .radio
                  %label
                    %input{:name => "optradio#{index}", "data-index"=>"1", :type => "radio",:class=>"option"}/
                  - if /.(jpeg|jpg|gif|png)$/.match(ques.option2)
                    = cl_image_tag(ques.option2,:class=>"img-thumbnail img-fluid")
                  - else
                    %font{:size => "4.5"}= ques.option2
                .radio
                  %label
                    %input{:name => "optradio#{index}", "data-index"=>"2", :type => "radio",:class=>"option"}/
                  - if /.(jpeg|jpg|gif|png)$/.match(ques.option3)
                    = cl_image_tag(ques.option3, :class=>"img-thumbnail img-fluid")
                  - else
                    %font{:size => "4.5"}= ques.option3
                .radio
                  %label
                    %input{:name => "optradio#{index}", "data-index"=>"3", :type => "radio",:class=>"option"}/
                  - if /.(jpeg|jpg|gif|png)$/.match(ques.option4)
                    = cl_image_tag(ques.option4,:class=>"img-thumbnail img-fluid")
                  - else
                    %font{:size => "4.5"}= ques.option4
                .radio
                  %label
                    %input{:name => "optradio#{index}", "data-index"=>"4", :type => "radio",:class=>"option"}/
                  - if /.(jpeg|jpg|gif|png)$/.match(ques.option5)
                    = cl_image_tag(ques.option5,:class=>"img-thumbnail img-fluid")
                  - else
                    %font{:size => "4.5"}= ques.option5
            %br/
        .row
          .col-xs-4
            .previous
              %button.btn.previous{:disabled => "disabled", :onclick => "getPrevious()", :type => "button"} Previous
          .col-xs-4.mx-auto
            %button.btn.btn-primary#showAnswerBtn{:onclick => "showAnswer()", :type => "button"} Show Answer
          .col-xs-4
            .next
              %button.btn.next{:onclick => "getNext()", :type => "button"} Next
      .row
        .col-xs-12.mx-auto
          %button.btn.btn-info#submitQuiz.hide{:type => "button",:disabled=>"disabled"} Submit

app/views/questions/edit.html.haml
%script{:src => "https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"}
= cloudinary_js_config
.container.createquestion
  %h2 Edit Question
  %hr/
  .row
    .col-md-10
      = form_tag question_path(@question),:id=>"createQuestionForm", :method=> :put do
        .form-group
          = label :question, :category, 'Question Category',class: "control-label"
          = select :question,:category, ['Networks', 'Algorithms', 'Operating Systems', 'Software'],{}, class:"form-control"
          
        - if /.(jpeg|jpg|gif|png)$/.match(@question.question)
          .form-group
            = label :question, :question, 'Question',class: "control-label"
            = cl_image_upload_tag(:imagequestion,:tags => "directly_uploaded_question",:crop => :limit, :width => 900, :height => 900,:eager => [{ :crop => :fill, :width => 750, :height => 240 }],:html => { :class=>"form-control fuquestion",:style => "margin-top: 8px" }  )
            .previewquestion
              = cl_image_tag(@question.question,:class=>"img-thumbnail img-fluid")
            .updatequestion
        - else
          .form-group
          = label :question, :question, 'Question',class: "control-label"
          = text_field :question, 'question', class:"form-control", autofocus: "true", placeholder: "Please add Question text or Image"
        
        - if /.(jpeg|jpg|gif|png)$/.match(@question.option1)
          .form-group
            = label :question, :option1, 'Option1',class: "control-label"
            = cl_image_upload_tag(:image1,:tags => "directly_uploaded",:crop => :limit, :width => 500, :height => 300,:eager => [{ :crop => :fill, :width => 350, :height => 70 }],:html => { :class=>"form-control fu1",:style => "margin-top: 8px" }  )
            .preview1
              = cl_image_tag(@question.option1,:class=>"img-thumbnail img-fluid")
            .update1
        - else
          .form-group
          = label :question, :option1, 'Option1',class: "control-label"
          = text_field :question, 'option1', class:"form-control", autofocus: "true", placeholder: "Please add option text or Image"
          
        - if /.(jpeg|jpg|gif|png)$/.match(@question.option2)
          .form-group
            = label :question, :option2, 'Option2',class: "control-label"
            = cl_image_upload_tag(:image2,:tags => "directly_uploaded",:crop => :limit, :width => 500, :height => 300,:eager => [{ :crop => :fill, :width => 350, :height => 70 }],:html => { :class=>"form-control fu2",:style => "margin-top: 8px" }  )
            .preview2
              = cl_image_tag(@question.option2, :class=>"img-thumbnail img-fluid")
            .update2
        - else
          .form-group
            = label :question, :option2, 'Option2',class: "control-label"
            = text_field :question, 'option2', class:"form-control", autofocus: "true", placeholder: "Please add option text or Image"
        
        - if /.(jpeg|jpg|gif|png)$/.match(@question.option3)
          .form-group
            = label :question, :option3, 'Option3',class: "control-label"
            = cl_image_upload_tag(:image3,:tags => "directly_uploaded",:crop => :limit, :width => 500, :height => 300,:eager => [{ :crop => :fill, :width => 350, :height => 70 }],:html => { :class=>"form-control fu3",:style => "margin-top: 8px" }  )
            .preview3
              = cl_image_tag(@question.option3, :class=>"img-thumbnail img-fluid")
            .update3
        - else
          .form-group
          = label :question, :option3, 'Option3',class: "control-label"
          = text_field :question, 'option3', class:"form-control", autofocus: "true", placeholder: "Please add option text or Image"
        
        - if /.(jpeg|jpg|gif|png)$/.match(@question.option4)
          .form-group
            = label :question, :option4, 'Option4',class: "control-label"
            = cl_image_upload_tag(:image4,:tags => "directly_uploaded",:crop => :limit, :width => 500, :height => 300,:eager => [{ :crop => :fill, :width => 350, :height => 70 }],:html => { :class=>"form-control fu4",:style => "margin-top: 8px" }  )
            .preview4
              = cl_image_tag(@question.option4, :class=>"img-thumbnail img-fluid")
            .update4
        - else
          .form-group
            = label :question, :option4, 'Option4',class: "control-label"
            = text_field :question, 'option4', class:"form-control", autofocus: "true", placeholder: "Please add option text or Image"
          
        - if /.(jpeg|jpg|gif|png)$/.match(@question.option5)
          .form-group
            = label :question, :option5, 'Option5',class: "control-label"
            = cl_image_upload_tag(:image5,:tags => "directly_uploaded",:crop => :limit, :width => 500, :height => 300,:eager => [{ :crop => :fill, :width => 350, :height => 70 }],:html => { :class=>"form-control fu5",:style => "margin-top: 8px" }  )
            .preview5
              = cl_image_tag(@question.option5, :class=>"img-thumbnail img-fluid")
            .update5
        - else
          .form-group 
            = label :question, :option5, 'Option5',class: "control-label"
            = text_field :question, 'option5', class:"form-control", autofocus: "true", placeholder: "Please add option text or Image"
      
        .form-group
          = label :question, :answer, 'Correct Answer',class: "control-label"
          = text_field :question, 'answer', class:"form-control", autofocus: "true", placeholder: "Please add correct option number. For e.g., If Option 1 is correct, put 1 in this field"
        .row
          .form-group.mx-auto
            = submit_tag 'Save Changes',class: "btn btn-primary"

app/views/questions/index.html.haml
%script{:src => "https://cdn.datatables.net/1.10.15/js/jquery.dataTables.js"}
%link{:href => "https://cdn.datatables.net/1.10.15/css/jquery.dataTables.css", :rel => "stylesheet"}/
%link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
.container
    - if !flash[:success].blank?
        .alert.alert-success.alert-dismissible.fade.show{:role=>"alert"}
            = flash[:success]
            %button.close{:type=>"button",:data=>{:dismiss=>"alert"},:aria=>{:label=>"Close"}}
                %span{:aria=>{:hidden=>"true"}} &times;
    - if !flash[:destroy].blank?
        .alert.alert-danger.alert-dismissible.fade.show{:role=>"alert"}
            = flash[:destroy]
            %button.close{:type=>"button",:data=>{:dismiss=>"alert"},:aria=>{:label=>"Close"}}
                %span{:aria=>{:hidden=>"true"}} &times;
    =link_to "Add new question", new_question_path,:class=>'btn btn-primary'
    .table-responsive.--margintop16#studentsTB
        %table{:id=>'students',:class=>'default table table-hover'}
            %thead
                %tr
                    %th Id
                    %th Title
                    %th Category
                    %th Edit
                    %th Delete
            %tbody
                - @questions.each_with_index do |ques,index|
                    %tr
                        %td= ques.id
                        %td.truncate= ques.question
                        %td= ques.category
                        %td
                            =link_to edit_question_path(ques) do
                                %i{:class=>'fa fa-edit'}
                        %td
                            =link_to question_path(ques),:method=>:delete, :data=>{:confirm=>"Are you sure you want to delete this question? "} do
                                %i{:class=>'fa fa-trash'}
   

app/views/questions/new.html.haml
%script{:src => "https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"}
= cloudinary_js_config
.container.createquestion
  %h2 Create New Question
  %hr/
  .row
    .col-md-10
      = form_tag questions_path,:id=>"createQuestionForm" do
        .form-group
          = label :question, :category, 'Question Category',class: "control-label"
          = select :question,:category, ['Networks', 'Algorithms', 'Operating Systems', 'Software'],{}, class:"form-control"
        .form-group
          = label :question, :question, 'Question',class: "control-label"
          = text_field :question, 'question', class:"form-control", autofocus: "true", placeholder: "Please add Question text or Image"
          = cl_image_upload_tag(:imagequestion,:tags => "directly_uploaded_question",:crop => :limit, :width => 900, :height => 900,:eager => [{ :crop => :fill, :width => 750, :height => 240 }],:html => { :class=>"form-control fuquestion",:style => "margin-top: 8px" }  )
          .updatequestion
        .form-group
          = label :question, :option1, 'Option1',class: "control-label"
          = text_field :question, 'option1', class:"form-control", autofocus: "true", placeholder: "Please add option text or Image"
          = cl_image_upload_tag(:image1,:tags => "directly_uploaded",:crop => :limit, :width => 500, :height => 300,:eager => [{ :crop => :fill, :width => 350, :height => 70 }],:html => { :class=>"form-control fu1",:style => "margin-top: 8px" }  )
          .update1
        .form-group
        = label :question, :option2, 'Option2',class: "control-label"
        = text_field :question, 'option2', class:"form-control", autofocus: "true", placeholder: "Please add option text or Image"
        = cl_image_upload_tag(:image2,:tags => "directly_uploaded",:crop => :limit, :width => 500, :height => 300,:eager => [{ :crop => :fill, :width => 350, :height => 70 }],:html => { :class=>"form-control fu2",:style => "margin-top: 8px" }  )
        .update2
        .form-group
          = label :question, :option3, 'Option3',class: "control-label"
          = text_field :question, 'option3', class:"form-control", autofocus: "true", placeholder: "Please add option text or Image"
          = cl_image_upload_tag(:image3,:tags => "directly_uploaded",:crop => :limit, :width => 500, :height => 300,:eager => [{ :crop => :fill, :width => 350, :height => 70 }],:html => { :class=>"form-control fu3",:style => "margin-top: 8px" }  )
          .update3
        .form-group
          = label :question, :option4, 'Option4',class: "control-label"
          = text_field :question, 'option4', class:"form-control", autofocus: "true", placeholder: "Please add option text or Image"
          = cl_image_upload_tag(:image4,:tags => "directly_uploaded",:crop => :limit, :width => 500, :height => 300,:eager => [{ :crop => :fill, :width => 350, :height => 70 }],:html => { :class=>"form-control fu4",:style => "margin-top: 8px" }  )
          .update4
        .form-group 
          = label :question, :option5, 'Option5',class: "control-label"
          = text_field :question, 'option5', class:"form-control", autofocus: "true", placeholder: "Please add option text or Image"
          = cl_image_upload_tag(:image5,:tags => "directly_uploaded",:crop => :limit, :width => 500, :height => 300,:eager => [{ :crop => :fill, :width => 350, :height => 70 }],:html => { :class=>"form-control fu5",:style => "margin-top: 8px" }  )
          .update5
        .form-group
          = label :question, :answer, 'Correct Answer',class: "control-label"
          = text_field :question, 'answer', class:"form-control", autofocus: "true", placeholder: "Please add correct option number. For e.g., If Option 1 is correct, put 1 in this field"
        .row
          .form-group.mx-auto
            = submit_tag 'Save Changes',class: "btn btn-primary"

app/views/quiz/index.html.haml
.container
  .row
    .col-md-12#quizContainer
      %article.jumbotron.mx-auto
        - @questions.each_with_index do |ques,index|
          .questionItem{:class=>"#{'hide' if index > 0}","data-answer" => "#{ques.answer}","data-index"=>"#{index}"}
            .row
              %span.h--serif Category: #{ques.category} | Question #{index+1} of #{@questions.count}
            .row
              - if /.(jpeg|jpg|gif|png)$/.match(ques.question)
                = cl_image_tag(ques.question, :class=>"img-thumbnail img-fluid")
              - else
                %h3= ques.question
            .row
              .choices
                .radio
                  %label
                    %input{:name => "optradio#{index}","data-index"=>"0", :type => "radio",:class=>"option"}/
                  - if /.(jpeg|jpg|gif|png)$/.match(ques.option1)
                    = cl_image_tag(ques.option1,:class=>"img-thumbnail img-fluid")
                  - else
                    %font{:size => "4.5"}= ques.option1
                .radio
                  %label
                    %input{:name => "optradio#{index}", "data-index"=>"1", :type => "radio",:class=>"option"}/
                  - if /.(jpeg|jpg|gif|png)$/.match(ques.option2)
                    = cl_image_tag(ques.option2, :class=>"img-thumbnail img-fluid")
                  - else
                    %font{:size => "4.5"}= ques.option2
                .radio
                  %label
                    %input{:name => "optradio#{index}", "data-index"=>"2", :type => "radio",:class=>"option"}/
                  - if /.(jpeg|jpg|gif|png)$/.match(ques.option3)
                    = cl_image_tag(ques.option3, :class=>"img-thumbnail img-fluid")
                  - else
                    %font{:size => "4.5"}= ques.option3
                .radio
                  %label
                    %input{:name => "optradio#{index}", "data-index"=>"3", :type => "radio",:class=>"option"}/
                  - if /.(jpeg|jpg|gif|png)$/.match(ques.option4)
                    = cl_image_tag(ques.option4,:class=>"img-thumbnail img-fluid")
                  - else
                    %font{:size => "4.5"}= ques.option4
                .radio
                  %label
                    %input{:name => "optradio#{index}", "data-index"=>"4", :type => "radio",:class=>"option"}/
                  - if /.(jpeg|jpg|gif|png)$/.match(ques.option5)
                    = cl_image_tag(ques.option5, :class=>"img-thumbnail img-fluid")
                  - else
                    %font{:size => "4.5"}= ques.option5
            %br/
        .row
          .col-xs-4
            .previous
              %button.btn.previous{:disabled => "disabled", :onclick => "getPrevious()", :type => "button"} Previous
          .col-xs-4.mx-auto
            %button.btn.btn-primary.hide#showAnswerBtn{:onclick => "showAnswer()", :type => "button"} Show Answer
          .col-xs-4
            .next
              %button.btn.next{:onclick => "getNext()", :type => "button"} Next
      .row
        .col-xs-12.mx-auto
          %button.btn.btn-info#submitQuiz{:type => "button",:disabled=>"disabled"} Submit

app/views/selcat/index.html.haml
.container.jumbotron
  %h1.row Select a Category
  .row
    = form_tag practice_path, :method => :get do
      - @all_categories.each do |category|
        .form-check
          = check_box_tag "categories[#{category}]",1,false, class: "form-check-input"
          %label.form-check-label #{category}
      .row
        .mx-auto
          = submit_tag 'Start Practice', name:nil, class: "btn btn-lg btn-primary --margintop16"
  

app/views/selquiz/index.html.haml
.container.jumbotron
  %h1.row Select number of questions
  .row
    = form_tag quiz_path, :method => :get do
      - @quizlimit.each do |limit|
        .form-check
          = radio_button_tag "quizlimit","#{limit}",false, class: "form-check-input"
          %label.form-check-label #{limit}
      .row
        .mx-auto
          = submit_tag 'Start Quiz', name:nil,class: "btn btn-lg btn-primary --margintop16"

app/views/users/new.html.haml
%h1 Users#new
%p Find me in app/views/users/new.html.haml

app/views/users/show.html.haml
.container
  - provide(:title, @user.name)
  %title
    = yield(:title)
    | Ruby on Rails Tutorial Sample App
  %p
    %li= link_to "Add a Question", new_question_path, :class=>'btn btn-primary'
    %li= link_to "Modify a Question",'#',:class=>'btn btn-warning'
    %li= link_to "Delete a Question",'#',:class=>'btn btn-danger'
   